import os
from functools import wraps
from urllib.parse import urlparse

import click
import psycopg2
import psycopg2.extras
from flask import (
    Flask,
    flash,
    g,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from werkzeug.security import check_password_hash, generate_password_hash


app = Flask(__name__)


def load_env_file(filename=".env"):
    if not os.path.exists(filename):
        return
    with open(filename, encoding="utf-8") as env_file:
        for line in env_file:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"'))


load_env_file()

app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "dev-only-change-me")
app.config["DATABASE_URL"] = os.environ.get(
    "DATABASE_URL", "postgresql://postgres:csh1q2w3e4r@localhost:5432/snickr"
)


def get_db():
    if "db" not in g:
        g.db = psycopg2.connect(
            app.config["DATABASE_URL"],
            cursor_factory=psycopg2.extras.RealDictCursor,
        )
    return g.db


@app.teardown_appcontext
def close_db(_error=None):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def query_all(sql, params=()):
    with get_db().cursor() as cur:
        cur.execute(sql, params)
        return cur.fetchall()


def query_one(sql, params=()):
    with get_db().cursor() as cur:
        cur.execute(sql, params)
        return cur.fetchone()


def ensure_bookmarks_schema():
    if app.config.get("BOOKMARKS_SCHEMA_READY"):
        return
    with get_db(), get_db().cursor() as cur:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS bookmarks (
                bookmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                label VARCHAR(160) NOT NULL,
                target_type VARCHAR(20) NOT NULL,
                target_url TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (user_id, target_url),
                CONSTRAINT bookmarks_type_ck
                    CHECK (target_type IN ('workspace', 'channel', 'search')),
                CONSTRAINT bookmarks_url_not_blank_ck
                    CHECK (length(btrim(target_url)) > 0)
            )
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_bookmarks_user_time
            ON bookmarks(user_id, created_at DESC, bookmark_id DESC)
            """
        )
    app.config["BOOKMARKS_SCHEMA_READY"] = True


def ensure_message_withdrawal_schema():
    if app.config.get("MESSAGE_WITHDRAWAL_SCHEMA_READY"):
        return
    with get_db(), get_db().cursor() as cur:
        cur.execute("ALTER TABLE messages ADD COLUMN IF NOT EXISTS withdrawn_at TIMESTAMPTZ")
        cur.execute(
            """
            ALTER TABLE messages
            ADD COLUMN IF NOT EXISTS withdrawn_by BIGINT REFERENCES users(user_id)
            """
        )
    app.config["MESSAGE_WITHDRAWAL_SCHEMA_READY"] = True


def normalize_bookmark_target(target_url):
    parsed = urlparse(target_url.strip())
    if parsed.scheme or parsed.netloc:
        return None
    if parsed.path.startswith("/workspaces/"):
        return "workspace", parsed.path
    if parsed.path.startswith("/channels/"):
        return "channel", parsed.path
    if parsed.path == "/search":
        query = f"?{parsed.query}" if parsed.query else ""
        return "search", parsed.path + query
    return None


def bookmark_for(target_url):
    ensure_bookmarks_schema()
    return query_one(
        """
        SELECT bookmark_id
        FROM bookmarks
        WHERE user_id = %s AND target_url = %s
        """,
        (g.user["user_id"], target_url),
    )


def login_required(view):
    @wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("login", next=request.path))
        return view(**kwargs)

    return wrapped_view


@app.before_request
def load_logged_in_user():
    user_id = session.get("user_id")
    g.user = None
    if user_id is not None:
        g.user = query_one(
            "SELECT user_id, email, username, nickname FROM users WHERE user_id = %s",
            (user_id,),
        )


def database_has_schema():
    row = query_one("SELECT to_regclass('public.users') AS users_table")
    return row and row["users_table"] is not None


@app.cli.command("init-db")
@click.option("--reset", is_flag=True, help="Drop and recreate existing tables.")
def init_db_command(reset):
    db = get_db()
    if database_has_schema() and not reset:
        click.echo(
            "Database already has snickr tables. Nothing changed. "
            "Run `flask --app app init-db --reset` if you want to rebuild sample data."
        )
        return
    with db, db.cursor() as cur:
        for filename in ("schema.sql", "sample_data.sql"):
            with open(filename, encoding="utf-8") as f:
                cur.execute(f.read())
    click.echo("Initialized the snickr database with schema.sql and sample_data.sql.")


def verify_password(stored_hash, password):
    if stored_hash.startswith(("scrypt:", "pbkdf2:", "argon2:")):
        return check_password_hash(stored_hash, password)
    return stored_hash == password


@app.route("/")
def index():
    if g.user:
        return redirect(url_for("dashboard"))
    return redirect(url_for("login"))


@app.route("/register", methods=("GET", "POST"))
def register():
    if request.method == "POST":
        email = request.form["email"].strip().lower()
        username = request.form["username"].strip()
        nickname = request.form["nickname"].strip()
        password = request.form["password"]
        if not email or not username or not nickname or not password:
            flash("All fields are required.", "error")
        else:
            try:
                with get_db(), get_db().cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO users(email, username, nickname, password_hash)
                        VALUES (%s, %s, %s, %s)
                        RETURNING user_id
                        """,
                        (email, username, nickname, generate_password_hash(password)),
                    )
                    user = cur.fetchone()
                session.clear()
                session["user_id"] = user["user_id"]
                flash("Your account is ready.", "success")
                return redirect(url_for("dashboard"))
            except psycopg2.IntegrityError:
                get_db().rollback()
                flash("That email or username is already in use.", "error")
    return render_template("register.html")


@app.route("/login", methods=("GET", "POST"))
def login():
    if request.method == "POST":
        username = request.form["username"].strip()
        password = request.form["password"]
        user = query_one(
            """
            SELECT user_id, username, nickname, password_hash
            FROM users
            WHERE username = %s OR email = %s
            """,
            (username, username.lower()),
        )
        if user and verify_password(user["password_hash"], password):
            session.clear()
            session["user_id"] = user["user_id"]
            return redirect(request.args.get("next") or url_for("dashboard"))
        flash("Invalid username/email or password.", "error")
    return render_template("login.html")


@app.route("/logout", methods=("POST",))
def logout():
    session.clear()
    return redirect(url_for("login"))


@app.route("/bookmarks", methods=("POST",))
@login_required
def add_bookmark():
    target = normalize_bookmark_target(request.form.get("target_url", ""))
    if target is None:
        flash("Only workspace, channel, and search pages can be bookmarked.", "error")
        return redirect(url_for("dashboard"))
    target_type, target_url = target
    label = request.form.get("label", "").strip() or target_url
    next_url = request.form.get("next", "").strip() or target_url
    ensure_bookmarks_schema()
    with get_db(), get_db().cursor() as cur:
        cur.execute(
            """
            INSERT INTO bookmarks(user_id, label, target_type, target_url)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (user_id, target_url) DO UPDATE
            SET label = EXCLUDED.label,
                target_type = EXCLUDED.target_type
            """,
            (g.user["user_id"], label[:160], target_type, target_url),
        )
    flash("Bookmark saved.", "success")
    return redirect(next_url if normalize_bookmark_target(next_url) else url_for("dashboard"))


@app.route("/bookmarks/delete", methods=("POST",))
@login_required
def delete_bookmark():
    target = normalize_bookmark_target(request.form.get("target_url", ""))
    next_url = request.form.get("next", "").strip()
    if target is None:
        flash("Bookmark not found.", "error")
        return redirect(url_for("dashboard"))
    _target_type, target_url = target
    ensure_bookmarks_schema()
    with get_db(), get_db().cursor() as cur:
        cur.execute(
            "DELETE FROM bookmarks WHERE user_id = %s AND target_url = %s",
            (g.user["user_id"], target_url),
        )
    flash("Bookmark removed.", "success")
    return redirect(next_url if normalize_bookmark_target(next_url) else url_for("dashboard"))


@app.route("/dashboard", methods=("GET", "POST"))
@login_required
def dashboard():
    if request.method == "POST":
        name = request.form["name"].strip()
        description = request.form["description"].strip()
        if not name:
            flash("Workspace name is required.", "error")
        else:
            try:
                with get_db(), get_db().cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO workspaces(name, description, created_by)
                        VALUES (%s, %s, %s)
                        RETURNING workspace_id
                        """,
                        (name, description, g.user["user_id"]),
                    )
                    workspace = cur.fetchone()
                    cur.execute(
                        """
                        INSERT INTO workspace_members(workspace_id, user_id, role)
                        VALUES (%s, %s, 'admin')
                        """,
                        (workspace["workspace_id"], g.user["user_id"]),
                    )
                flash("Workspace created.", "success")
                return redirect(url_for("workspace", workspace_id=workspace["workspace_id"]))
            except psycopg2.IntegrityError:
                get_db().rollback()
                flash("A workspace with that name already exists.", "error")

    workspaces = query_all(
        """
        SELECT w.workspace_id, w.name, w.description, wm.role,
               COUNT(DISTINCT cm.channel_id) AS joined_channels
        FROM workspace_members AS wm
        JOIN workspaces AS w ON w.workspace_id = wm.workspace_id
        LEFT JOIN channels AS c ON c.workspace_id = w.workspace_id
        LEFT JOIN channel_members AS cm
          ON cm.channel_id = c.channel_id AND cm.user_id = wm.user_id
        WHERE wm.user_id = %s
        GROUP BY w.workspace_id, w.name, w.description, wm.role
        ORDER BY w.name
        """,
        (g.user["user_id"],),
    )
    workspace_invites = query_all(
        """
        SELECT wi.workspace_invitation_id, w.name AS workspace, u.username AS invited_by,
               wi.invited_at
        FROM workspace_invitations AS wi
        JOIN workspaces AS w ON w.workspace_id = wi.workspace_id
        JOIN users AS u ON u.user_id = wi.invited_by
        WHERE wi.status = 'pending'
          AND (wi.invited_user_id = %s OR lower(wi.invited_email) = lower(%s))
        ORDER BY wi.invited_at
        """,
        (g.user["user_id"], g.user["email"]),
    )
    channel_invites = query_all(
        """
        SELECT ci.channel_invitation_id, c.name AS channel, w.name AS workspace,
               u.username AS invited_by, ci.invited_at
        FROM channel_invitations AS ci
        JOIN channels AS c ON c.channel_id = ci.channel_id
        JOIN workspaces AS w ON w.workspace_id = c.workspace_id
        JOIN users AS u ON u.user_id = ci.invited_by
        JOIN workspace_members AS wm
          ON wm.workspace_id = c.workspace_id AND wm.user_id = ci.invited_user_id
        WHERE ci.status = 'pending' AND ci.invited_user_id = %s
        ORDER BY ci.invited_at
        """,
        (g.user["user_id"],),
    )
    ensure_bookmarks_schema()
    bookmarks = query_all(
        """
        SELECT bookmark_id, label, target_type, target_url, created_at
        FROM bookmarks
        WHERE user_id = %s
        ORDER BY created_at DESC, bookmark_id DESC
        """,
        (g.user["user_id"],),
    )
    return render_template(
        "dashboard.html",
        workspaces=workspaces,
        workspace_invites=workspace_invites,
        channel_invites=channel_invites,
        bookmarks=bookmarks,
    )


def workspace_membership(workspace_id):
    return query_one(
        """
        SELECT role
        FROM workspace_members
        WHERE workspace_id = %s AND user_id = %s
        """,
        (workspace_id, g.user["user_id"]),
    )


def unique_usernames(usernames):
    seen = set()
    unique = []
    for username in usernames:
        if username not in seen:
            seen.add(username)
            unique.append(username)
    return unique


def workspace_invitee_rows(workspace_id, usernames):
    if not usernames:
        return []
    return query_all(
        """
        SELECT u.user_id, u.username
        FROM users AS u
        JOIN workspace_members AS wm ON wm.user_id = u.user_id
        WHERE wm.workspace_id = %s
          AND u.username = ANY(%s)
        """,
        (workspace_id, usernames),
    )


@app.route("/workspaces/<int:workspace_id>", methods=("GET", "POST"))
@login_required
def workspace(workspace_id):
    membership = workspace_membership(workspace_id)
    if membership is None:
        flash("You are not a member of that workspace.", "error")
        return redirect(url_for("dashboard"))

    workspace_row = query_one(
        "SELECT workspace_id, name, description FROM workspaces WHERE workspace_id = %s",
        (workspace_id,),
    )
    if request.method == "POST":
        channel_name = request.form["channel_name"].strip()
        channel_type = request.form["channel_type"]
        invitees = unique_usernames(
            [u.strip() for u in request.form.get("invitees", "").split(",") if u.strip()]
        )
        if not channel_name:
            flash("Channel name is required.", "error")
        elif channel_type not in {"public", "private", "direct"}:
            flash("Invalid channel type.", "error")
        else:
            invitee_rows = workspace_invitee_rows(workspace_id, invitees)
            if invitees:
                found_usernames = {row["username"] for row in invitee_rows}
                invalid_invitees = [
                    username for username in invitees if username not in found_usernames
                ]
                if invalid_invitees:
                    flash(
                        "Cannot invite users who are not members of this workspace: "
                        + ", ".join(invalid_invitees),
                        "error",
                    )
                    return redirect(url_for("workspace", workspace_id=workspace_id))
            if channel_type == "direct":
                other_invitees = [
                    row for row in invitee_rows if row["user_id"] != g.user["user_id"]
                ]
                if len(other_invitees) != 1:
                    flash("Direct channels must include exactly one other workspace member.", "error")
                    return redirect(url_for("workspace", workspace_id=workspace_id))
            try:
                with get_db(), get_db().cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO channels(workspace_id, name, channel_type, created_by)
                        VALUES (%s, %s, %s, %s)
                        RETURNING channel_id
                        """,
                        (workspace_id, channel_name, channel_type, g.user["user_id"]),
                    )
                    channel = cur.fetchone()
                    cur.execute(
                        "INSERT INTO channel_members(channel_id, user_id) VALUES (%s, %s)",
                        (channel["channel_id"], g.user["user_id"]),
                    )
                    if channel_type == "direct":
                        cur.execute(
                            """
                            INSERT INTO channel_members(channel_id, user_id)
                            VALUES (%s, %s)
                            ON CONFLICT (channel_id, user_id) DO NOTHING
                            """,
                            (channel["channel_id"], other_invitees[0]["user_id"]),
                        )
                    else:
                        for invitee in invitee_rows:
                            if invitee["user_id"] == g.user["user_id"]:
                                continue
                            cur.execute(
                                """
                                INSERT INTO channel_invitations(
                                    channel_id, invited_user_id, invited_by
                                )
                                VALUES (%s, %s, %s)
                                ON CONFLICT (channel_id, invited_user_id) DO NOTHING
                                """,
                                (
                                    channel["channel_id"],
                                    invitee["user_id"],
                                    g.user["user_id"],
                                ),
                            )
                flash("Channel created.", "success")
                return redirect(url_for("channel", channel_id=channel["channel_id"]))
            except psycopg2.IntegrityError:
                get_db().rollback()
                flash("That channel name already exists in this workspace.", "error")

    channels = query_all(
        """
        SELECT c.channel_id, c.name, c.channel_type, c.created_at,
               (cm.user_id IS NOT NULL) AS is_member,
               COUNT(m.message_id) AS message_count
        FROM channels AS c
        LEFT JOIN channel_members AS cm
          ON cm.channel_id = c.channel_id AND cm.user_id = %s
        LEFT JOIN messages AS m ON m.channel_id = c.channel_id
        WHERE c.workspace_id = %s
          AND (c.channel_type = 'public' OR cm.user_id IS NOT NULL)
        GROUP BY c.channel_id, c.name, c.channel_type, c.created_at, cm.user_id
        ORDER BY c.channel_type, c.name
        """,
        (g.user["user_id"], workspace_id),
    )
    members = query_all(
        """
        SELECT u.username, u.nickname, wm.role
        FROM workspace_members AS wm
        JOIN users AS u ON u.user_id = wm.user_id
        WHERE wm.workspace_id = %s
        ORDER BY wm.role, u.username
        """,
        (workspace_id,),
    )
    return render_template(
        "workspace.html",
        workspace=workspace_row,
        membership=membership,
        channels=channels,
        members=members,
        bookmarked=bookmark_for(url_for("workspace", workspace_id=workspace_id)),
        bookmark_url=url_for("workspace", workspace_id=workspace_id),
    )


@app.route("/workspaces/<int:workspace_id>/invite", methods=("POST",))
@login_required
def invite_workspace(workspace_id):
    membership = workspace_membership(workspace_id)
    if membership is None or membership["role"] != "admin":
        flash("Only workspace admins can invite workspace members.", "error")
        return redirect(url_for("workspace", workspace_id=workspace_id))
    invitee_text = request.form["invitee"].strip()
    if not invitee_text:
        flash("Enter an email address or username.", "error")
        return redirect(url_for("workspace", workspace_id=workspace_id))
    if "@" in invitee_text:
        invitee = query_one(
            "SELECT user_id, email FROM users WHERE lower(email) = lower(%s)",
            (invitee_text.lower(),),
        )
        invited_email = invitee["email"] if invitee else invitee_text.lower()
    else:
        invitee = query_one(
            "SELECT user_id, email FROM users WHERE username = %s",
            (invitee_text,),
        )
        if invitee is None:
            flash("No user with that username exists. Use an email address to invite a new user.", "error")
            return redirect(url_for("workspace", workspace_id=workspace_id))
        invited_email = invitee["email"]
    try:
        with get_db(), get_db().cursor() as cur:
            cur.execute(
                """
                INSERT INTO workspace_invitations(
                    workspace_id, invited_email, invited_user_id, invited_by
                )
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (workspace_id, invited_email) DO NOTHING
                """,
                (
                    workspace_id,
                    invited_email,
                    invitee["user_id"] if invitee else None,
                    g.user["user_id"],
                ),
            )
        flash("Workspace invitation recorded.", "success")
    except psycopg2.Error:
        get_db().rollback()
        flash("Could not create that invitation.", "error")
    return redirect(url_for("workspace", workspace_id=workspace_id))


@app.route("/workspace-invitations/<int:invitation_id>/<decision>", methods=("POST",))
@login_required
def respond_workspace_invitation(invitation_id, decision):
    if decision not in {"accepted", "declined"}:
        flash("Invalid invitation response.", "error")
        return redirect(url_for("dashboard"))
    invitation = query_one(
        """
        SELECT workspace_invitation_id, workspace_id
        FROM workspace_invitations
        WHERE workspace_invitation_id = %s
          AND status = 'pending'
          AND (invited_user_id = %s OR lower(invited_email) = lower(%s))
        """,
        (invitation_id, g.user["user_id"], g.user["email"]),
    )
    if invitation is None:
        flash("Invitation not found.", "error")
        return redirect(url_for("dashboard"))
    with get_db(), get_db().cursor() as cur:
        cur.execute(
            """
            UPDATE workspace_invitations
            SET status = %s, responded_at = CURRENT_TIMESTAMP
            WHERE workspace_invitation_id = %s
            """,
            (decision, invitation_id),
        )
        if decision == "accepted":
            cur.execute(
                """
                INSERT INTO workspace_members(workspace_id, user_id, role)
                VALUES (%s, %s, 'member')
                ON CONFLICT (workspace_id, user_id) DO NOTHING
                """,
                (invitation["workspace_id"], g.user["user_id"]),
            )
    flash("Invitation response saved.", "success")
    return redirect(url_for("dashboard"))


@app.route("/channels/<int:channel_id>", methods=("GET", "POST"))
@login_required
def channel(channel_id):
    ensure_message_withdrawal_schema()
    channel_row = query_one(
        """
        SELECT c.channel_id, c.name, c.channel_type, c.workspace_id, w.name AS workspace,
               (cm.user_id IS NOT NULL) AS is_member
        FROM channels AS c
        JOIN workspaces AS w ON w.workspace_id = c.workspace_id
        JOIN workspace_members AS wm
          ON wm.workspace_id = c.workspace_id AND wm.user_id = %s
        LEFT JOIN channel_members AS cm
          ON cm.channel_id = c.channel_id AND cm.user_id = %s
        WHERE c.channel_id = %s
          AND (c.channel_type = 'public' OR cm.user_id IS NOT NULL)
        """,
        (g.user["user_id"], g.user["user_id"], channel_id),
    )
    if channel_row is None:
        flash("You are not a member of that channel.", "error")
        return redirect(url_for("dashboard"))
    if channel_row["channel_type"] == "public" and not channel_row["is_member"]:
        with get_db(), get_db().cursor() as cur:
            cur.execute(
                """
                INSERT INTO channel_members(channel_id, user_id)
                VALUES (%s, %s)
                ON CONFLICT (channel_id, user_id) DO NOTHING
                """,
                (channel_id, g.user["user_id"]),
            )
        channel_row["is_member"] = True
    if request.method == "POST":
        body = request.form["body"].strip()
        if not body:
            flash("Message body cannot be blank.", "error")
        else:
            with get_db(), get_db().cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO messages(channel_id, sender_id, body)
                    VALUES (%s, %s, %s)
                    """,
                    (channel_id, g.user["user_id"], body),
                )
            flash("Message posted.", "success")
            return redirect(url_for("channel", channel_id=channel_id))
    messages = query_all(
        """
        SELECT m.message_id, m.body, m.posted_at, m.sender_id, m.withdrawn_at,
               u.username, u.nickname
        FROM messages AS m
        JOIN users AS u ON u.user_id = m.sender_id
        WHERE m.channel_id = %s
        ORDER BY m.posted_at, m.message_id
        """,
        (channel_id,),
    )
    members = query_all(
        """
        SELECT u.username, u.nickname
        FROM channel_members AS cm
        JOIN users AS u ON u.user_id = cm.user_id
        WHERE cm.channel_id = %s
        ORDER BY u.username
        """,
        (channel_id,),
    )
    return render_template(
        "channel.html",
        channel=channel_row,
        messages=messages,
        members=members,
        bookmarked=bookmark_for(url_for("channel", channel_id=channel_id)),
        bookmark_url=url_for("channel", channel_id=channel_id),
    )


@app.route("/channels/<int:channel_id>/messages.json")
@login_required
def channel_messages_json(channel_id):
    ensure_message_withdrawal_schema()
    try:
        after = int(request.args.get("after", 0))
    except ValueError:
        after = 0
    channel_row = query_one(
        """
        SELECT c.channel_id, c.channel_type
        FROM channels AS c
        JOIN workspace_members AS wm
          ON wm.workspace_id = c.workspace_id AND wm.user_id = %s
        LEFT JOIN channel_members AS cm
          ON cm.channel_id = c.channel_id AND cm.user_id = %s
        WHERE c.channel_id = %s
          AND (c.channel_type = 'public' OR cm.user_id IS NOT NULL)
        """,
        (g.user["user_id"], g.user["user_id"], channel_id),
    )
    if channel_row is None:
        return jsonify({"messages": []}), 403
    messages = query_all(
        """
        SELECT m.message_id, m.body, m.posted_at, m.sender_id, m.withdrawn_at,
               u.username, u.nickname
        FROM messages AS m
        JOIN users AS u ON u.user_id = m.sender_id
        WHERE m.channel_id = %s
          AND m.message_id > %s
        ORDER BY m.posted_at, m.message_id
        LIMIT 100
        """,
        (channel_id, after),
    )
    return jsonify(
        {
            "messages": [
                {
                    "message_id": message["message_id"],
                    "body": message["body"],
                    "posted_at": message["posted_at"].strftime("%Y-%m-%d %H:%M"),
                    "sender_id": message["sender_id"],
                    "username": message["username"],
                    "nickname": message["nickname"],
                    "withdrawn": message["withdrawn_at"] is not None,
                }
                for message in messages
            ]
        }
    )


@app.route("/messages/<int:message_id>/withdraw", methods=("POST",))
@login_required
def withdraw_message(message_id):
    ensure_message_withdrawal_schema()
    message = query_one(
        """
        SELECT m.message_id, m.sender_id, m.channel_id, m.withdrawn_at,
               c.workspace_id, c.channel_type
        FROM messages AS m
        JOIN channels AS c ON c.channel_id = m.channel_id
        JOIN workspace_members AS wm
          ON wm.workspace_id = c.workspace_id AND wm.user_id = %s
        LEFT JOIN channel_members AS cm
          ON cm.channel_id = c.channel_id AND cm.user_id = %s
        WHERE m.message_id = %s
          AND (c.channel_type = 'public' OR cm.user_id IS NOT NULL)
        """,
        (g.user["user_id"], g.user["user_id"], message_id),
    )
    if message is None:
        flash("Message not found.", "error")
        return redirect(url_for("dashboard"))
    if message["sender_id"] != g.user["user_id"]:
        flash("You can only withdraw your own messages.", "error")
        return redirect(url_for("channel", channel_id=message["channel_id"]))
    if message["withdrawn_at"] is None:
        with get_db(), get_db().cursor() as cur:
            cur.execute(
                """
                UPDATE messages
                SET withdrawn_at = CURRENT_TIMESTAMP,
                    withdrawn_by = %s
                WHERE message_id = %s
                  AND sender_id = %s
                  AND withdrawn_at IS NULL
                """,
                (g.user["user_id"], message_id, g.user["user_id"]),
            )
        flash("Message withdrawn.", "success")
    else:
        flash("That message was already withdrawn.", "error")
    return redirect(url_for("channel", channel_id=message["channel_id"]))


@app.route("/channels/<int:channel_id>/invite", methods=("POST",))
@login_required
def invite_channel(channel_id):
    channel_row = query_one(
        """
        SELECT c.channel_id, c.workspace_id, c.channel_type
        FROM channels AS c
        JOIN channel_members AS cm
          ON cm.channel_id = c.channel_id AND cm.user_id = %s
        WHERE c.channel_id = %s
        """,
        (g.user["user_id"], channel_id),
    )
    if channel_row is None:
        flash("You must belong to a channel before inviting others.", "error")
        return redirect(url_for("dashboard"))
    if channel_row["channel_type"] == "direct":
        flash("Direct channels are limited to their original participants.", "error")
        return redirect(url_for("channel", channel_id=channel_id))
    username = request.form["username"].strip()
    invitee = query_one(
        """
        SELECT u.user_id
        FROM users AS u
        JOIN workspace_members AS wm ON wm.user_id = u.user_id
        WHERE u.username = %s AND wm.workspace_id = %s
        """,
        (username, channel_row["workspace_id"]),
    )
    if invitee is None:
        flash("That user is not a member of this workspace.", "error")
    else:
        with get_db(), get_db().cursor() as cur:
            cur.execute(
                """
                INSERT INTO channel_invitations(channel_id, invited_user_id, invited_by)
                VALUES (%s, %s, %s)
                ON CONFLICT (channel_id, invited_user_id) DO NOTHING
                """,
                (channel_id, invitee["user_id"], g.user["user_id"]),
            )
        flash("Channel invitation recorded.", "success")
    return redirect(url_for("channel", channel_id=channel_id))


@app.route("/channel-invitations/<int:invitation_id>/<decision>", methods=("POST",))
@login_required
def respond_channel_invitation(invitation_id, decision):
    if decision not in {"accepted", "declined"}:
        flash("Invalid invitation response.", "error")
        return redirect(url_for("dashboard"))
    invitation = query_one(
        """
        SELECT ci.channel_invitation_id, ci.channel_id, c.workspace_id
        FROM channel_invitations AS ci
        JOIN channels AS c ON c.channel_id = ci.channel_id
        WHERE ci.channel_invitation_id = %s
          AND ci.status = 'pending'
          AND ci.invited_user_id = %s
        """,
        (invitation_id, g.user["user_id"]),
    )
    if invitation is None:
        flash("Invitation not found.", "error")
        return redirect(url_for("dashboard"))
    if decision == "accepted" and workspace_membership(invitation["workspace_id"]) is None:
        flash("Join the workspace before accepting that channel invitation.", "error")
        return redirect(url_for("dashboard"))
    with get_db(), get_db().cursor() as cur:
        cur.execute(
            """
            UPDATE channel_invitations
            SET status = %s, responded_at = CURRENT_TIMESTAMP
            WHERE channel_invitation_id = %s
            """,
            (decision, invitation_id),
        )
        if decision == "accepted":
            cur.execute(
                """
                INSERT INTO channel_members(channel_id, user_id)
                VALUES (%s, %s)
                ON CONFLICT (channel_id, user_id) DO NOTHING
                """,
                (invitation["channel_id"], g.user["user_id"]),
            )
    flash("Invitation response saved.", "success")
    return redirect(url_for("dashboard"))


@app.route("/search")
@login_required
def search():
    ensure_message_withdrawal_schema()
    keyword = request.args.get("q", "").strip()
    results = []
    if keyword:
        results = query_all(
            """
            SELECT m.message_id, m.body, m.posted_at, u.username,
                   c.channel_id, c.name AS channel, w.name AS workspace
            FROM messages AS m
            JOIN channels AS c ON c.channel_id = m.channel_id
            JOIN workspaces AS w ON w.workspace_id = c.workspace_id
            JOIN users AS u ON u.user_id = m.sender_id
            JOIN workspace_members AS wm
              ON wm.workspace_id = w.workspace_id AND wm.user_id = %s
            LEFT JOIN channel_members AS cm
              ON cm.channel_id = c.channel_id AND cm.user_id = %s
            WHERE m.body ILIKE '%%' || %s || '%%'
              AND (c.channel_type = 'public' OR cm.user_id IS NOT NULL)
              AND m.withdrawn_at IS NULL
            ORDER BY m.posted_at DESC, m.message_id DESC
            """,
            (g.user["user_id"], g.user["user_id"], keyword),
        )
    bookmark_url = url_for("search", q=keyword) if keyword else None
    return render_template(
        "search.html",
        keyword=keyword,
        results=results,
        bookmarked=bookmark_for(bookmark_url) if bookmark_url else None,
        bookmark_url=bookmark_url,
    )


if __name__ == "__main__":
    app.run(debug=True)
